# Generated by Django 3.1.7 on 2022-02-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('service', models.CharField(choices=[('J', 'Journal'), ('P', 'Panneau'), ('C', 'Chaine')], default='', max_length=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('client', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Afficheur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_afficheur', models.CharField(blank=True, max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annonceur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Apc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_APC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chaine')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJournal', models.CharField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(default='', upload_to='media')),
                ('NomAnnonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
            ],
        ),
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Unipol', 'Unipol'), ('Sucette', 'Sucette'), ('Abri-Bus', 'Abri-Bus'), ('Bus', 'Bus'), ('Sucette dynamique', 'Sucette dynamique'), ('Terasse', 'Terasse'), ('Fassade', 'Fassade')], max_length=20)),
                ('itineraire', models.CharField(max_length=20)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField()),
                ('designation', models.CharField(max_length=40)),
                ('hauteur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('elevation', models.FloatField()),
                ('nbpub', models.IntegerField()),
                ('mecanisme', models.CharField(choices=[('Dérouleur', 'Dérouleur'), ('Trivision', 'Trivision'), ('Fix', 'Fix')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('afficheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.afficheur')),
                ('apc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apc')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(default='', upload_to='media')),
                ('NomMarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_wilaya', models.CharField(max_length=30)),
                ('num_wilaya', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='media')),
                ('debut', models.TimeField()),
                ('duree', models.DurationField()),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('encombrement', models.IntegerField(blank=True, null=True)),
                ('ecran', models.IntegerField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais')], default='', max_length=2)),
                ('message', models.CharField(default='', max_length=120)),
                ('confirmed', models.BooleanField(default=False)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jour')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('fr', 'fr'), ('ar', 'ar'), ('fr + ar', 'fr + ar')], max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='media')),
                ('confirmed', models.BooleanField(default=False)),
                ('circulation', models.BooleanField(default=True)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.panneau')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=120)),
                ('debut', models.TimeField()),
                ('duree', models.DurationField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='media')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.abonnement')),
                ('annonceurs', models.ManyToManyField(to='api.Annonceur')),
                ('marques', models.ManyToManyField(blank=True, null=True, to='api.Marque')),
                ('produits', models.ManyToManyField(blank=True, null=True, to='api.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(max_length=50)),
                ('Wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media')),
                ('date_creation', models.DateField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais')], default='', max_length=2)),
                ('accroche', models.CharField(default='', max_length=10000)),
                ('page_suivante', models.CharField(choices=[('s', 'sport'), ('p', 'politeque'), ('c', 'culture')], default='', max_length=1)),
                ('page_precedente', models.CharField(choices=[('s', 'sport'), ('p', 'politeque'), ('c', 'culture')], default='', max_length=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edition')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.AddField(
            model_name='apc',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune'),
        ),
    ]
