# Generated by Django 3.1.7 on 2022-02-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chaine')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=120)),
                ('debut', models.TimeField()),
                ('duree', models.DurationField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='media')),
                ('debut', models.TimeField()),
                ('duree', models.DurationField()),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('encombrement', models.IntegerField(blank=True, null=True)),
                ('ecran', models.IntegerField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais')], default='', max_length=2)),
                ('message', models.CharField(default='', max_length=120)),
                ('confirmed', models.BooleanField(default=False)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jour')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoPub',
        ),
    ]
